export PATH="/opt/nvim-linux-x86_64/bin:$PATH"
. "$HOME/.local/bin/env"
eval "$(starship init zsh)"

function y() {
    local tmp cwd
    tmp="$(mktemp -t "yazi-cwd.XXXXXX")"

    command yazi "$@" --cwd-file="$tmp"

    IFS= read -r -d '' cwd < "$tmp"

    if [[ -n "$cwd" && "$cwd" != "$PWD" ]]; then
        builtin cd -- "$cwd"
    fi

    rm -f "$tmp"
}

# Homebrew
if command -v brew >/dev/null 2>&1; then
  eval "$(brew shellenv)"

  if [[ -d "$(brew --prefix llvm 2>/dev/null)/bin" ]]; then
    export PATH="$(brew --prefix llvm)/bin:$PATH"
  fi

  if [[ -d "$(brew --prefix openjdk@21 2>/dev/null)/bin" ]]; then
    export PATH="$(brew --prefix openjdk@21)/bin:$PATH"
  fi
fi
